// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714174856_RemoveDeadRoleColumnFromUsers")]
    partial class RemoveDeadRoleColumnFromUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Entities.Annotation.Annotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_annotation");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6424),
                            Description = "Nokta oluşturma yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6425),
                            Name = "point_create"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6427),
                            Description = "Çizgi oluşturma yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6427),
                            Name = "line_create"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6429),
                            Description = "Poligon oluşturma yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6429),
                            Name = "polygon_create"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6430),
                            Description = "Admin paneli erişim yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6430),
                            Name = "admin_access"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6431),
                            Description = "Not/işaret ekleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6431),
                            Name = "annotation_create"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6432),
                            Description = "Not geçmişini görüntüleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6432),
                            Name = "annotation_read"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6433),
                            Description = "POI oluşturma/güncelleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6434),
                            Name = "poi_create"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6435),
                            Description = "POI görüntüleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6435),
                            Name = "poi_read"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6436),
                            Description = "POI kategori ağacını yönetme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6436),
                            Name = "poi_category_manage"
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6265),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6268),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6271),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6272),
                            Name = "Çalışan"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6273),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6273),
                            Name = "Stajyer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6274),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6274),
                            Name = "Takım Lideri"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6275),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6275),
                            Name = "Operator"
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 8
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.GeoPermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("BoundaryGeometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tbl_geo_permission");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.LineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("tbl_line");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.PointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("tbl_point");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.PolygonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("tbl_polygon");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.RoleGeoPermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("GeoPermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "GeoPermissionId");

                    b.HasIndex("GeoPermissionId");

                    b.ToTable("tbl_role_geo_permission");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.UserGeoPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GeoPermissionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GeoPermissionId");

                    b.HasIndex("GeoPermissionId");

                    b.ToTable("tbl_user_geo_permission");
                });

            modelBuilder.Entity("BackendApi.Entities.Poi.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_poi");
                });

            modelBuilder.Entity("BackendApi.Entities.Poi.PoiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("tbl_poi_category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6571),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6572),
                            Name = "Yeme İçme"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6573),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6573),
                            Name = "Restoran",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6574),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6574),
                            Name = "Kafe",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6575),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6575),
                            Name = "Turizm"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6576),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 14, 17, 48, 56, 373, DateTimeKind.Utc).AddTicks(6576),
                            Name = "Müze",
                            ParentCategoryId = 4
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.Team.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tbl_team");
                });

            modelBuilder.Entity("BackendApi.Entities.Annotation.Annotation", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackendApi.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("BackendApi.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.User", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.UserPermission", b =>
                {
                    b.HasOne("BackendApi.Entities.Auth.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("BackendApi.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.LineEntity", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.PointEntity", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.PolygonEntity", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.RoleGeoPermission", b =>
                {
                    b.HasOne("BackendApi.Entities.Geo.GeoPermissionEntity", "GeoPermission")
                        .WithMany("RoleGeoPermissions")
                        .HasForeignKey("GeoPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoPermission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.UserGeoPermission", b =>
                {
                    b.HasOne("BackendApi.Entities.Geo.GeoPermissionEntity", "GeoPermission")
                        .WithMany("UserGeoPermissions")
                        .HasForeignKey("GeoPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoPermission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Entities.Poi.Poi", b =>
                {
                    b.HasOne("BackendApi.Entities.Poi.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Entities.Poi.PoiCategory", b =>
                {
                    b.HasOne("BackendApi.Entities.Poi.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.User", b =>
                {
                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.GeoPermissionEntity", b =>
                {
                    b.Navigation("RoleGeoPermissions");

                    b.Navigation("UserGeoPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
