// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723113808_AddDurationSecondsToTransitRoute")]
    partial class AddDurationSecondsToTransitRoute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Entities.Annotation.Annotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_annotation");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(622),
                            Description = "Nokta oluşturma yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(622),
                            Name = "point_create"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(625),
                            Description = "Çizgi oluşturma yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(626),
                            Name = "line_create"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(627),
                            Description = "Poligon oluşturma yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(628),
                            Name = "polygon_create"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(629),
                            Description = "Admin paneli erişim yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(629),
                            Name = "admin_access"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(631),
                            Description = "Not/işaret ekleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(631),
                            Name = "annotation_create"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(632),
                            Description = "Not geçmişini görüntüleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(633),
                            Name = "annotation_read"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(634),
                            Description = "POI oluşturma/güncelleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(634),
                            Name = "poi_create"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(636),
                            Description = "POI görüntüleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(636),
                            Name = "poi_read"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(637),
                            Description = "POI kategori ağacını yönetme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(638),
                            Name = "poi_category_manage"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(639),
                            Description = "Durak oluşturma/güncelleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(639),
                            Name = "transit_stop_create"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(640),
                            Description = "Durak/güzergah görüntüleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(641),
                            Name = "transit_stop_read"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(642),
                            Description = "Güzergah yönetme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(642),
                            Name = "transit_route_manage"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(644),
                            Description = "Alan tarama analizi yapma yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(644),
                            Name = "area_scan"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(645),
                            Description = "Konum analizi yapma yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(646),
                            Name = "location_analysis"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(647),
                            Description = "Isı haritası görüntüleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(647),
                            Name = "heatmap_view"
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(425),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(429),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(433),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(433),
                            Name = "Çalışan"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(435),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(435),
                            Name = "Stajyer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(436),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(437),
                            Name = "Takım Lideri"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(438),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(438),
                            Name = "POI Operatörü"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(439),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(440),
                            Name = "Kullanıcı"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(441),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(441),
                            Name = "Ulaşım Operatörü"
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 12
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.GeoPermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("BoundaryGeometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tbl_geo_permission");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.LineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("tbl_line");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.PointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("tbl_point");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.PolygonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("tbl_polygon");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.RoleGeoPermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("GeoPermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "GeoPermissionId");

                    b.HasIndex("GeoPermissionId");

                    b.ToTable("tbl_role_geo_permission");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.UserGeoPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GeoPermissionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GeoPermissionId");

                    b.HasIndex("GeoPermissionId");

                    b.ToTable("tbl_user_geo_permission");
                });

            modelBuilder.Entity("BackendApi.Entities.Poi.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_poi");
                });

            modelBuilder.Entity("BackendApi.Entities.Poi.PoiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("tbl_poi_category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(863),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(863),
                            Name = "Yeme İçme"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(865),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(866),
                            Name = "Restoran",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(867),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(867),
                            Name = "Kafe",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(869),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(869),
                            Name = "Turizm"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(870),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 23, 11, 38, 8, 115, DateTimeKind.Utc).AddTicks(870),
                            Name = "Müze",
                            ParentCategoryId = 4
                        });
                });

            modelBuilder.Entity("BackendApi.Entities.Team.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tbl_team");
                });

            modelBuilder.Entity("BackendApi.Entities.Transit.TransitRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("RouteGeometry")
                        .HasColumnType("geometry");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_transit_route");
                });

            modelBuilder.Entity("BackendApi.Entities.Transit.TransitStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TransitRouteId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TransitRouteId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_transit_stop");
                });

            modelBuilder.Entity("BackendApi.Entities.Annotation.Annotation", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackendApi.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("BackendApi.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.User", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.UserPermission", b =>
                {
                    b.HasOne("BackendApi.Entities.Auth.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("BackendApi.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.LineEntity", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.PointEntity", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.PolygonEntity", b =>
                {
                    b.HasOne("BackendApi.Entities.Team.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.RoleGeoPermission", b =>
                {
                    b.HasOne("BackendApi.Entities.Geo.GeoPermissionEntity", "GeoPermission")
                        .WithMany("RoleGeoPermissions")
                        .HasForeignKey("GeoPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoPermission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.UserGeoPermission", b =>
                {
                    b.HasOne("BackendApi.Entities.Geo.GeoPermissionEntity", "GeoPermission")
                        .WithMany("UserGeoPermissions")
                        .HasForeignKey("GeoPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoPermission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApi.Entities.Poi.Poi", b =>
                {
                    b.HasOne("BackendApi.Entities.Poi.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Entities.Poi.PoiCategory", b =>
                {
                    b.HasOne("BackendApi.Entities.Poi.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BackendApi.Entities.Transit.TransitRoute", b =>
                {
                    b.HasOne("BackendApi.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BackendApi.Entities.Transit.TransitStop", b =>
                {
                    b.HasOne("BackendApi.Entities.Transit.TransitRoute", null)
                        .WithMany()
                        .HasForeignKey("TransitRouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendApi.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BackendApi.Entities.Auth.User", b =>
                {
                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BackendApi.Entities.Geo.GeoPermissionEntity", b =>
                {
                    b.Navigation("RoleGeoPermissions");

                    b.Navigation("UserGeoPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
